name: linting

on: push

jobs:
  linting:
    runs-on: ubuntu-latest
    setps:
      -name: Checkout code
      uses: actions/checkout@v2

      -name: install python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

      -name: install flake8
      run:
       python -m pip install --upgrade pip
       pip install flake8
      -name: run flake8
      run: flake8 app.py




    
